# Generated by Django 4.2.11 on 2025-08-24 15:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city_of_origin",
            field=models.CharField(
                default="Dhaka", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+8801876381867",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
