# Generated by Django 4.2.11 on 2025-08-24 17:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_city_of_origin_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                default="BD", max_length=180, verbose_name="Country"
            ),
        ),
    ]
