# Generated by Django 4.2.11 on 2025-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_country_of_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("mason", "Mason"),
                    ("carpenter", "Carpenter"),
                    ("plumber", "Plumber"),
                    ("roofer", "Roofer"),
                    ("painter", "Painter"),
                    ("electrician", "Electrician"),
                    ("hvac", "HVAC"),
                    ("teanant", "TENANT"),
                ],
                default="teanant",
                max_length=20,
                verbose_name="Occupation",
            ),
        ),
    ]
